import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '../lib/i18n';
import ClientLanguageProvider from "@/components/ClientLanguageProvider";
import Head from "next/head"; // i18n should only handle initialization here

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SemanticMap",
  description: "Generated by semanticmap",
};


export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClientLanguageProvider>
          <Head>
              {/* Add the Plausible script */}
              <script defer data-domain="semanticmap.com" src="https://plausible.io/js/script.tagged-events.js"></script>
          </Head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {children}
        </body>
      </ClientLanguageProvider>
  );
}