name: Update README with timestamp

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Update README with timestamp
      run: |
        echo "Last updated on $(date)" >> README.md

    - name: Commit changes
      run: |
        git add README.md
        git commit -m "Update README with timestamp"
        git push
